### ISSUE TITLE
求问大佬，如何直接获取生成的sql语句呢？

### ISSUE THREAD

**Issue by 1148330040** [Crossme0809/langchain-tutorials#1]
![1691462443275](https://github.com/Crossme0809/langchain-tutorials/assets/34124260/68ecc320-7169-4c29-b5f0-679c200d703d)
看图片，它是类似于字典的形式进行的数据展示，因此，有没有办法直接通过key来获取sql的value呢？

**Comment by Crossme0809** [comment]
从LangChain官方仓库中了解了一下，该功能在 v0.0.239 版本中增加了直接返回SQL查询脚本的支持。 最新的版本似乎去掉了这块功能。
<img width="1016" alt="image" src="https://github.com/Crossme0809/langchain-tutorials/assets/134267461/320ade04-193a-4e76-8d9c-ba826c33d770">

issue：https://github.com/langchain-ai/langchain/issues/4853
commit：https://github.com/langchain-ai/langchain/commit/355b7d8b8603ea9c543dbf5db62ce3148a3d78d6

调用只需要传入 return_sql = true 即可

<img width="1340" alt="image" src="https://github.com/Crossme0809/langchain-tutorials/assets/134267461/42579cf3-3776-4fb3-815c-fd56ec019157">
